/*
 * DlgInicioSesion.java
 */
package interfaz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import objetosNegocio.Usuario;

/**
 * @author HectorEspinoza, RicardoGutierrez, AdrianaGutierrez, VictoriaVega
 */
public class DlgPuntajes extends javax.swing.JDialog {

    /**
     * Creates new form DlgInicioSesion
     *
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo
     * @param modal true si permite acceder fuera de los límites del cuadro de
     * diálogo, false en caso contrario
     */
    public DlgPuntajes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setResizable(false);
        setTitle("High Scores");
        initComponents();
        centraCuadroDialogo(parent);
        panelInicioSesion.setBackground(new Color(0, 0, 0, 150));
        jPanel2.setBackground(new Color(0, 0, 0, 0));
        ArrayList<String> puntajes = new ArrayList<>();
        puntajes = leerArchivo();

        lblHighScores.setFont(new Font("Pixel Digivolve", Font.PLAIN, 50));
        lblPuntajes.setFont(new Font("Pixel Digivolve", Font.PLAIN, 20));
        lblUsuarios.setFont(new Font("Pixel Digivolve", Font.PLAIN, 20));
        puntaje1.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        puntaje2.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        puntaje3.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        puntaje4.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        puntaje5.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        usuario1.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        usuario2.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        usuario3.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        usuario4.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        usuario5.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));

        usuario1.setText(puntajes.get(0));
        puntaje1.setText(puntajes.get(1));
        usuario2.setText(puntajes.get(2));
        puntaje2.setText(puntajes.get(3));
        usuario3.setText(puntajes.get(4));
        puntaje3.setText(puntajes.get(5));
        usuario4.setText(puntajes.get(6));
        puntaje4.setText(puntajes.get(7));
        usuario5.setText(puntajes.get(8));
        puntaje5.setText(puntajes.get(9));
        btnCerrar.setFont(new Font("Pixel Digivolve", Font.PLAIN, 12));

        setVisible(true);
    }

    /**
     * Permite leer el archivo de highscores donde se encuentran los usuarios
     * con mejor puntaje y regresa una lista con la información.
     *
     * @return Una lista con la información de los usuarios con mejor puntaje.
     */
    public static ArrayList<String> leerArchivo() {
        String rutaArchivo = "archivosUsuarios/highScores.dat";
        ArrayList<String> lineas = new ArrayList<>();

        try (BufferedReader lector = new BufferedReader(new FileReader(rutaArchivo))) {
            String linea;
            while ((linea = lector.readLine()) != null) {
                lineas.add(linea);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return lineas;
    }

    /**
     * Este método centra el cuadro de dialogo sobre la ventana de la
     * aplicación.
     *
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo
     */
    private void centraCuadroDialogo(java.awt.Frame parent) {
        // Obtiene el tamaño y posición de la ventana de la aplicación
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();
        // Obtiene el tamaño del cuadro de diálogo
        Dimension dlgSize = getPreferredSize();
        // Centra el cuadro de diálogo sobre la ventana padre
        setLocation((frameSize.width - dlgSize.width) / 2 + loc.x, (frameSize.height - dlgSize.height) / 2 + loc.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblHighScores = new javax.swing.JLabel();
        panelInicioSesion = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        lblUsuarios = new javax.swing.JLabel();
        lblPuntajes = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        usuario2 = new javax.swing.JLabel();
        usuario3 = new javax.swing.JLabel();
        usuario4 = new javax.swing.JLabel();
        usuario5 = new javax.swing.JLabel();
        puntaje1 = new javax.swing.JLabel();
        puntaje2 = new javax.swing.JLabel();
        puntaje3 = new javax.swing.JLabel();
        puntaje4 = new javax.swing.JLabel();
        puntaje5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHighScores.setBackground(new java.awt.Color(255, 255, 255));
        lblHighScores.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        lblHighScores.setForeground(new java.awt.Color(255, 255, 0));
        lblHighScores.setText("High Scores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(lblHighScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblHighScores)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 570, 70));

        panelInicioSesion.setBackground(new java.awt.Color(0, 0, 0));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(153, 153, 153));
        btnCerrar.setText("Close");
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(255, 51, 51));
        lblUsuarios.setText("Users");

        lblPuntajes.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        lblPuntajes.setForeground(new java.awt.Color(255, 51, 51));
        lblPuntajes.setText("Scores");

        usuario1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        usuario1.setForeground(new java.awt.Color(153, 153, 153));
        usuario1.setText("Empty");

        usuario2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        usuario2.setForeground(new java.awt.Color(153, 153, 153));
        usuario2.setText("Empty");

        usuario3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        usuario3.setForeground(new java.awt.Color(153, 153, 153));
        usuario3.setText("Empty");

        usuario4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        usuario4.setForeground(new java.awt.Color(153, 153, 153));
        usuario4.setText("Empty");

        usuario5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        usuario5.setForeground(new java.awt.Color(153, 153, 153));
        usuario5.setText("Empty");

        puntaje1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        puntaje1.setForeground(new java.awt.Color(153, 153, 153));
        puntaje1.setText("Empty");

        puntaje2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        puntaje2.setForeground(new java.awt.Color(153, 153, 153));
        puntaje2.setText("Empty");

        puntaje3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        puntaje3.setForeground(new java.awt.Color(153, 153, 153));
        puntaje3.setText("Empty");

        puntaje4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        puntaje4.setForeground(new java.awt.Color(153, 153, 153));
        puntaje4.setText("Empty");

        puntaje5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        puntaje5.setForeground(new java.awt.Color(153, 153, 153));
        puntaje5.setText("Empty");

        javax.swing.GroupLayout panelInicioSesionLayout = new javax.swing.GroupLayout(panelInicioSesion);
        panelInicioSesion.setLayout(panelInicioSesionLayout);
        panelInicioSesionLayout.setHorizontalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(17, 17, 17))
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarios)
                    .addComponent(usuario1)
                    .addComponent(usuario5)
                    .addComponent(usuario4)
                    .addComponent(usuario3)
                    .addComponent(usuario2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuntajes)
                    .addComponent(puntaje1)
                    .addComponent(puntaje2)
                    .addComponent(puntaje3)
                    .addComponent(puntaje4)
                    .addComponent(puntaje5))
                .addGap(120, 120, 120))
        );
        panelInicioSesionLayout.setVerticalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarios)
                    .addComponent(lblPuntajes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario1)
                    .addComponent(puntaje1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario2)
                    .addComponent(puntaje2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario3)
                    .addComponent(puntaje3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario4)
                    .addComponent(puntaje4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario5)
                    .addComponent(puntaje5))
                .addGap(42, 42, 42)
                .addComponent(btnCerrar)
                .addGap(16, 16, 16))
        );

        getContentPane().add(panelInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 430));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/fondoDlgPuntajes.gif"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método oyente del botón Cerrar.
     *
     * @param evt Evento al que escucha.
     */
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHighScores;
    private javax.swing.JLabel lblPuntajes;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel panelInicioSesion;
    private javax.swing.JLabel puntaje1;
    private javax.swing.JLabel puntaje2;
    private javax.swing.JLabel puntaje3;
    private javax.swing.JLabel puntaje4;
    private javax.swing.JLabel puntaje5;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario2;
    private javax.swing.JLabel usuario3;
    private javax.swing.JLabel usuario4;
    private javax.swing.JLabel usuario5;
    // End of variables declaration//GEN-END:variables
    private Usuario[] bestScoresUsers;
}
