/*
 * DlgInicioSesion.java
 */
package interfaz;

import control.Validadores;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import javax.swing.JOptionPane;
import objetosNegocio.Usuario;

/**
 * @author HectorEspinoza, RicardoGutierrez, AdrianaGutierrez, VictoriaVega
 */
public class DlgRegistroUsuario extends javax.swing.JDialog {

    /**
     * Creates new form DlgInicioSesion
     *
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo
     * @param modal true si permite acceder fuera de los límites del cuadro de
     * diálogo, false en caso contrario
     * @param usuario El usuario a capturar.
     * @param respuesta Boton presionado al salir de los cuadros de diálogos:
     * ACEPTAR = "Aceptar", CANCELAR = "Cancelar"
     */
    public DlgRegistroUsuario(java.awt.Frame parent, boolean modal, Usuario usuario,
            StringBuffer respuesta) {
        super(parent, modal);
        this.setResizable(false);
        setTitle("Sign Up");
        initComponents();
        centraCuadroDialogo(parent);
        lblInicioSesion.setFont(new Font("Pixel Digivolve", Font.PLAIN, 50));
        panelInicioSesion.setBackground(new Color(0, 0, 0, 150));
        txtFieldNombre.setBackground(new Color(153, 153, 153, 100));
        txtFieldUsuario.setBackground(new Color(153, 153, 153, 100));
        passwordFieldContrasenia.setBackground(new Color(153, 153, 153, 100));
        passwordFieldConfirmarContrasenia.setBackground(new Color(153, 153, 153, 100));
        jPanel2.setBackground(new Color(0, 0, 0, 0));
        
        lblInicioSesion.setFont(new Font("Pixel Digivolve", Font.PLAIN, 50));
        lblNombre.setFont(new Font("Pixel Digivolve", Font.PLAIN, 19));
        lblUsuario.setFont(new Font("Pixel Digivolve", Font.PLAIN, 19));
        lblContrasenia.setFont(new Font("Pixel Digivolve", Font.PLAIN, 19));
        lblContrasenia1.setFont(new Font("Pixel Digivolve", Font.PLAIN, 19));
        jLabel1.setFont(new Font("Pixel Digivolve", Font.PLAIN, 10));
        jLabel2.setFont(new Font("Pixel Digivolve", Font.PLAIN, 10));
        jLabel3.setFont(new Font("Pixel Digivolve", Font.PLAIN, 10));
        btnAceptar.setFont(new Font("Pixel Digivolve", Font.PLAIN, 12));
        btnCancelar.setFont(new Font("Pixel Digivolve", Font.PLAIN, 12));
        
        this.usuario = usuario;
        this.respuesta = respuesta;
        setVisible(true);
    }

    /**
     * Este método centra el cuadro de dialogo sobre la ventana de la
     * aplicación.
     *
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo
     */
    private void centraCuadroDialogo(java.awt.Frame parent) {
        // Obtiene el tamaño y posición de la ventana de la aplicación
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();
        // Obtiene el tamaño del cuadro de diálogo
        Dimension dlgSize = getPreferredSize();
        // Centra el cuadro de diálogo sobre la ventana padre
        setLocation((frameSize.width - dlgSize.width) / 2 + loc.x, (frameSize.height - dlgSize.height) / 2 + loc.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicioSesion = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtFieldUsuario = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passwordFieldContrasenia = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtFieldNombre = new javax.swing.JTextField();
        passwordFieldConfirmarContrasenia = new javax.swing.JPasswordField();
        lblContrasenia1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInicioSesion = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicioSesion.setBackground(new java.awt.Color(0, 0, 0));
        panelInicioSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        lblUsuario.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblUsuario.setText("User Name:");

        lblContrasenia.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(204, 204, 204));
        lblContrasenia.setText("Password:");

        txtFieldUsuario.setBackground(new java.awt.Color(153, 153, 153));
        txtFieldUsuario.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        txtFieldUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(153, 153, 153));
        btnAceptar.setText("Accept");
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(153, 153, 153));
        btnCancelar.setText("Cancel");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("(Maximum of 15 characters)");

        passwordFieldContrasenia.setBackground(new java.awt.Color(153, 153, 153));
        passwordFieldContrasenia.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        passwordFieldContrasenia.setForeground(new java.awt.Color(204, 204, 204));
        passwordFieldContrasenia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("(Minimun of 8 characters)");

        lblNombre.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Name:");

        txtFieldNombre.setBackground(new java.awt.Color(153, 153, 153));
        txtFieldNombre.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        txtFieldNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        passwordFieldConfirmarContrasenia.setBackground(new java.awt.Color(153, 153, 153));
        passwordFieldConfirmarContrasenia.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        passwordFieldConfirmarContrasenia.setForeground(new java.awt.Color(204, 204, 204));
        passwordFieldConfirmarContrasenia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        lblContrasenia1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        lblContrasenia1.setForeground(new java.awt.Color(204, 204, 204));
        lblContrasenia1.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("(Confirm password)");

        javax.swing.GroupLayout panelInicioSesionLayout = new javax.swing.GroupLayout(panelInicioSesion);
        panelInicioSesion.setLayout(panelInicioSesionLayout);
        panelInicioSesionLayout.setHorizontalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioSesionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(40, 40, 40))
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioSesionLayout.createSequentialGroup()
                        .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioSesionLayout.createSequentialGroup()
                        .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContrasenia)
                            .addComponent(lblContrasenia1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordFieldConfirmarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordFieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))))
                .addGap(15, 15, 15))
        );
        panelInicioSesionLayout.setVerticalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordFieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordFieldConfirmarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(17, 17, 17))
        );

        getContentPane().add(panelInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 430, 280));

        lblInicioSesion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        lblInicioSesion.setForeground(new java.awt.Color(255, 255, 0));
        lblInicioSesion.setText("Sign Up");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(lblInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblInicioSesion)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 570, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/fondoDlgInicioSesion.gif"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 710, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método oyente del botón Aceptar.
     *
     * @param evt Evento al que escucha.
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // Si alguno de los campos de texto o contraseñas están vacíos.
        if (txtFieldNombre.getText().isBlank() || txtFieldUsuario.getText().isBlank()
                || passwordFieldContrasenia.getText().isBlank() || passwordFieldConfirmarContrasenia.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Make sure to fill in all fields.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            // Si el nombre no es válido.
            if (!validador.validarNombre(txtFieldNombre.getText())) {
                JOptionPane.showMessageDialog(this, "Make sure to enter a valid name.",
                        "Warning", JOptionPane.WARNING_MESSAGE);

                // Si el usuario no es válido.
            } else if (!validador.validarUsuario(txtFieldUsuario.getText())) {
                JOptionPane.showMessageDialog(this, "Make sure your user only uses uppercase, lowercase,\n '.' (not consecutive) and '_'.",
                        "Warning", JOptionPane.WARNING_MESSAGE);

                // Si la contraseña no es válida.    
            } else if (!validador.validarContrasenia(passwordFieldContrasenia.getText())) {
                JOptionPane.showMessageDialog(this, "Make sure your password has at least one uppercase,\n one lowercase, one number and one special character.",
                        "Warning", JOptionPane.WARNING_MESSAGE);

                // Si las contraseñas no coinciden.
            } else if (!validador.validarConfirmarContrasenia(passwordFieldContrasenia.getText(), passwordFieldConfirmarContrasenia.getText())) {
                JOptionPane.showMessageDialog(this, "Make sure both passwords match.",
                        "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                usuario.setNombre(txtFieldNombre.getText());
                usuario.setUsuario(txtFieldUsuario.getText());
                usuario.setContrasenia(passwordFieldContrasenia.getText());

                // Borra el contenido de respuesta
                respuesta.delete(0, respuesta.length());
                // Establece que se presionó el botón botonAceptar
                respuesta.append(ConstantesGUI.ACEPTAR);
                // Destruye el cuadro de díalogo
                dispose();
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * Método oyente del botón Cancelar.
     *
     * @param evt Evento al que escucha.
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Destruye el cuadro de dialogo
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblContrasenia1;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelInicioSesion;
    private javax.swing.JPasswordField passwordFieldConfirmarContrasenia;
    private javax.swing.JPasswordField passwordFieldContrasenia;
    private javax.swing.JTextField txtFieldNombre;
    private javax.swing.JTextField txtFieldUsuario;
    // End of variables declaration//GEN-END:variables
    private Usuario usuario;
    private StringBuffer respuesta;
    private Validadores validador = new Validadores();
}
