/*
 * FrmMenuPrincipal.java
 */
package interfaz;

import control.Control;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Font;
import java.net.URL;
import javax.swing.JOptionPane;
import objetosNegocio.Usuario;

/**
 * @author HectorEspinoza, RicardoGutierrez, AdrianaGutierrez, VictoriaVega
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates a new FrmMenuPrincipal form.
     */
    public FrmMenuPrincipal() {
        setTitle("Crazy Driver 2077");
        initComponents();
        this.setSize(864, 516);
        btnIniciarSesion.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        btnCerrarSesion.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        btnScores.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        btnRegistrarUsuario.setFont(new Font("Pixel Digivolve", Font.PLAIN, 18));
        btnJugarPartida.setFont(new Font("Pixel Digivolve", Font.PLAIN, 23));

        btnSalir.setOpaque(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setBorderPainted(false);
        rutaFondo = getClass().getResource("/multimedia/musicaInicio.wav");
        musicaFondo = Applet.newAudioClip(rutaFondo);

        musicaFondo.loop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrarUsuario = new javax.swing.JButton();
        btnJugarPartida = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnScores = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(864, 516));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesion.setBackground(new java.awt.Color(102, 0, 102));
        btnIniciarSesion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 0, 255));
        btnIniciarSesion.setText("Sign In");
        btnIniciarSesion.setFocusPainted(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, -1));

        btnRegistrarUsuario.setBackground(new java.awt.Color(102, 0, 102));
        btnRegistrarUsuario.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        btnRegistrarUsuario.setForeground(new java.awt.Color(255, 0, 255));
        btnRegistrarUsuario.setText("Sign Up");
        btnRegistrarUsuario.setFocusPainted(false);
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 150, -1));

        btnJugarPartida.setBackground(new java.awt.Color(204, 0, 204));
        btnJugarPartida.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 23)); // NOI18N
        btnJugarPartida.setForeground(new java.awt.Color(255, 153, 255));
        btnJugarPartida.setText("Play");
        btnJugarPartida.setFocusPainted(false);
        btnJugarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 40));

        btnCerrarSesion.setBackground(new java.awt.Color(102, 0, 102));
        btnCerrarSesion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 0, 255));
        btnCerrarSesion.setText("Sign Out");
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 150, -1));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/btnSalirImagen.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        btnScores.setBackground(new java.awt.Color(102, 0, 102));
        btnScores.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        btnScores.setForeground(new java.awt.Color(255, 0, 255));
        btnScores.setText("High Scores");
        btnScores.setFocusPainted(false);
        btnScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 150, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/fondoFrmMenuPrincipal.gif"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método oyente del botón IniciarSesion.
     *
     * @param evt Evento al que escucha.
     */
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        if (usuario == null) {
            usuario = control.iniciarSesion(this);
        } else {
            JOptionPane.showMessageDialog(rootPane, "A session is already started.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * Método oyente del botón RegistrarUsuario.
     *
     * @param evt Evento al que escucha.
     */
    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        control.registrarUsuario(this);
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    /**
     * Método oyente del botón Salir.
     *
     * @param evt Evento al que escucha.
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Método oyente del botón JugarPartida.
     *
     * @param evt Evento al que escucha.
     */
    private void btnJugarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarPartidaActionPerformed
        if (usuario == null) {
            JOptionPane.showMessageDialog(this, "Must be signed in before playing a game.",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            musicaFondo.stop();
            control.jugarPartida(this, usuario);
        }
    }//GEN-LAST:event_btnJugarPartidaActionPerformed

    /**
     * Método oyente del botón CerrarSesion.
     *
     * @param evt Evento al que escucha.
     */
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        if (usuario != null) {
            usuario = null;
            JOptionPane.showMessageDialog(rootPane, "Successfully signed out.",
                    "Signed Out", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No user is signed in.",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * Método oyente del botón Scores.
     *
     * @param evt Evento al que escucha.
     */
    private void btnScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoresActionPerformed
        control.mostrarHighScores(this);
    }//GEN-LAST:event_btnScoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnJugarPartida;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnScores;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
    private URL rutaFondo;
    public static AudioClip musicaFondo;
    private Control control = new Control();
}
