/*
 * DlgPuntaje.java
 */
package elementosJuego;

import control.Control;
import interfaz.FrmMenuPrincipal;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import objetosNegocio.Usuario;

/**
 * @author HectorEspinoza, RicardoGutierrez, AdrianaGutierrez, VictoriaVega
 */
public class DlgJuegoTerminado extends javax.swing.JDialog {

    private int puntos;
    private Usuario usuario;

    /**
     * Creates new form DlgPuntaje
     *
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo.
     * @param modal true si permite acceder fuera de los límites del cuadro de
     * diálogo, false en caso contrario.
     * @param usuario El usuario que jugó el juego.
     * @param puntos El mejor puntaje del usuario.
     */
    public DlgJuegoTerminado(java.awt.Frame parent, boolean modal, Usuario usuario, int puntos) {
        super(parent, modal);
        this.usuario = usuario;
        this.puntos = puntos;
        initComponents();
        lblPuntaje.setText(Integer.toString(puntos));
        lblUsuario.setText(usuario.getUsuario());
        jPanel1.setBackground(new Color(0, 0, 0, 150));
        
        lblUser.setFont(new Font("Pixel Digivolve", Font.PLAIN, 24));
        lblScore.setFont(new Font("Pixel Digivolve", Font.PLAIN, 24));
        lblGameOver.setFont(new Font("Pixel Digivolve", Font.PLAIN, 60));
        btnAceptar.setFont(new Font("Pixel Digivolve", Font.PLAIN, 16));
        lblPuntaje.setFont(new Font("Pixel Digivolve", Font.PLAIN, 24));
        lblUsuario.setFont(new Font("Pixel Digivolve", Font.PLAIN, 24));
        
        centraCuadroDialogo(parent);
        setTitle("Game Over");
        setSize(500, 335);
        setResizable(false);
        setVisible(true);
    }

    /**
     * Este método centra el cuadro de dialogo sobre la ventana de la
     * aplicación.
     *
     * @param parent Ventana sobre la que aparecerá el cuadro de diálogo
     */
    private void centraCuadroDialogo(java.awt.Frame parent) {
        // Obtiene el tamaño y posición de la ventana de la aplicación
        Dimension frameSize = parent.getSize();
        Point loc = parent.getLocation();
        // Obtiene el tamaño del cuadro de diálogo
        Dimension dlgSize = getPreferredSize();
        // Centra el cuadro de diálogo sobre la ventana padre
        setLocation((frameSize.width - dlgSize.width) / 2 + loc.x, (frameSize.height - dlgSize.height) / 2 + loc.y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGameOver = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        lblGameOver.setBackground(new java.awt.Color(255, 255, 255));
        lblGameOver.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 60)); // NOI18N
        lblGameOver.setForeground(new java.awt.Color(255, 0, 0));
        lblGameOver.setText("GAME OVER");
        lblGameOver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblGameOver.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblGameOver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblScore.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 26)); // NOI18N
        lblScore.setForeground(new java.awt.Color(0, 102, 153));
        lblScore.setText("SCORE:");

        lblPuntaje.setBackground(new java.awt.Color(0, 0, 0));
        lblPuntaje.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 26)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblPuntaje.setText("0");

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 26)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 153, 204));
        lblUser.setText("USER:");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblUsuario.setText("richi.ast");

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(153, 153, 153));
        btnAceptar.setText("Close");
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGameOver)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblScore)
                            .addComponent(lblUser))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGameOver)
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblScore)
                            .addComponent(lblPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 310));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/fondoDlgGameOver.gif"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método oyente del botón Aceptar.
     *
     * @param evt El evento al que escucha.
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Control control = new Control();
        control.verificarPuntosUsuarios(usuario.getScore(), usuario);
        control.escribirPuntajeArchivo(usuario);
        FrmMenuPrincipal.musicaFondo.loop();
        Auto.x = 400;
        Auto.y = 500;
        Auto.desplazamiento = 5;
        Obstaculo.y = -200;
        Obstaculo1.y = -560;
        Juego.fin = false;
        Juego.velocidad = 5;
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGameOver;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
